name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Checkout  
      uses: actions/checkout@v2  
      with:  
          fetch-depth: 0  
    - name: Version  
      id: version  
      uses: juliansangillo/tag-version@v1  
      with:  
          production-branch: main  
          dev-branch: feat/*  

